package com.yibaieducation.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yibaieducation.bean.Ti_paper;
import com.yibaieducation.bean.Ti_title;
import com.yibaieducation.bean.Ti_title_parent;
import com.yibaieducation.bean.Ti_item;
import com.yibaieducation.bean.Ti_item_config;
import com.yibaieducation.bean.Ti_sku_subject;
import com.yibaieducation.bean.Ti_account_types;
import com.yibaieducation.bean.Ti_account_subs;

import com.yibaieducation.dao.Ti_paperDao;
import com.yibaieducation.dao.Ti_titleDao;
import com.yibaieducation.dao.Ti_title_parentDao;
import com.yibaieducation.dao.Ti_itemDao;
import com.yibaieducation.dao.Ti_item_configDao;
import com.yibaieducation.dao.Ti_sku_subjectDao;
import com.yibaieducation.dao.Ti_account_typesDao;
import com.yibaieducation.dao.Ti_account_subsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ti_paperDaoConfig;
    private final DaoConfig ti_titleDaoConfig;
    private final DaoConfig ti_title_parentDaoConfig;
    private final DaoConfig ti_itemDaoConfig;
    private final DaoConfig ti_item_configDaoConfig;
    private final DaoConfig ti_sku_subjectDaoConfig;
    private final DaoConfig ti_account_typesDaoConfig;
    private final DaoConfig ti_account_subsDaoConfig;

    private final Ti_paperDao ti_paperDao;
    private final Ti_titleDao ti_titleDao;
    private final Ti_title_parentDao ti_title_parentDao;
    private final Ti_itemDao ti_itemDao;
    private final Ti_item_configDao ti_item_configDao;
    private final Ti_sku_subjectDao ti_sku_subjectDao;
    private final Ti_account_typesDao ti_account_typesDao;
    private final Ti_account_subsDao ti_account_subsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ti_paperDaoConfig = daoConfigMap.get(Ti_paperDao.class).clone();
        ti_paperDaoConfig.initIdentityScope(type);

        ti_titleDaoConfig = daoConfigMap.get(Ti_titleDao.class).clone();
        ti_titleDaoConfig.initIdentityScope(type);

        ti_title_parentDaoConfig = daoConfigMap.get(Ti_title_parentDao.class).clone();
        ti_title_parentDaoConfig.initIdentityScope(type);

        ti_itemDaoConfig = daoConfigMap.get(Ti_itemDao.class).clone();
        ti_itemDaoConfig.initIdentityScope(type);

        ti_item_configDaoConfig = daoConfigMap.get(Ti_item_configDao.class).clone();
        ti_item_configDaoConfig.initIdentityScope(type);

        ti_sku_subjectDaoConfig = daoConfigMap.get(Ti_sku_subjectDao.class).clone();
        ti_sku_subjectDaoConfig.initIdentityScope(type);

        ti_account_typesDaoConfig = daoConfigMap.get(Ti_account_typesDao.class).clone();
        ti_account_typesDaoConfig.initIdentityScope(type);

        ti_account_subsDaoConfig = daoConfigMap.get(Ti_account_subsDao.class).clone();
        ti_account_subsDaoConfig.initIdentityScope(type);

        ti_paperDao = new Ti_paperDao(ti_paperDaoConfig, this);
        ti_titleDao = new Ti_titleDao(ti_titleDaoConfig, this);
        ti_title_parentDao = new Ti_title_parentDao(ti_title_parentDaoConfig, this);
        ti_itemDao = new Ti_itemDao(ti_itemDaoConfig, this);
        ti_item_configDao = new Ti_item_configDao(ti_item_configDaoConfig, this);
        ti_sku_subjectDao = new Ti_sku_subjectDao(ti_sku_subjectDaoConfig, this);
        ti_account_typesDao = new Ti_account_typesDao(ti_account_typesDaoConfig, this);
        ti_account_subsDao = new Ti_account_subsDao(ti_account_subsDaoConfig, this);

        registerDao(Ti_paper.class, ti_paperDao);
        registerDao(Ti_title.class, ti_titleDao);
        registerDao(Ti_title_parent.class, ti_title_parentDao);
        registerDao(Ti_item.class, ti_itemDao);
        registerDao(Ti_item_config.class, ti_item_configDao);
        registerDao(Ti_sku_subject.class, ti_sku_subjectDao);
        registerDao(Ti_account_types.class, ti_account_typesDao);
        registerDao(Ti_account_subs.class, ti_account_subsDao);
    }
    
    public void clear() {
        ti_paperDaoConfig.getIdentityScope().clear();
        ti_titleDaoConfig.getIdentityScope().clear();
        ti_title_parentDaoConfig.getIdentityScope().clear();
        ti_itemDaoConfig.getIdentityScope().clear();
        ti_item_configDaoConfig.getIdentityScope().clear();
        ti_sku_subjectDaoConfig.getIdentityScope().clear();
        ti_account_typesDaoConfig.getIdentityScope().clear();
        ti_account_subsDaoConfig.getIdentityScope().clear();
    }

    public Ti_paperDao getTi_paperDao() {
        return ti_paperDao;
    }

    public Ti_titleDao getTi_titleDao() {
        return ti_titleDao;
    }

    public Ti_title_parentDao getTi_title_parentDao() {
        return ti_title_parentDao;
    }

    public Ti_itemDao getTi_itemDao() {
        return ti_itemDao;
    }

    public Ti_item_configDao getTi_item_configDao() {
        return ti_item_configDao;
    }

    public Ti_sku_subjectDao getTi_sku_subjectDao() {
        return ti_sku_subjectDao;
    }

    public Ti_account_typesDao getTi_account_typesDao() {
        return ti_account_typesDao;
    }

    public Ti_account_subsDao getTi_account_subsDao() {
        return ti_account_subsDao;
    }

}
